In [3]:
import grid2op

from ray.rllib.agents import ppo
from ray.rllib.models import ModelCatalog

from models.mlp import SimpleMlp
from grid2op_env.grid_to_gym import Grid_Gym
# import model registry from rllib


ModelCatalog.register_custom_model("fcn", SimpleMlp)

/opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/redis/connection.py:72: UserWarning: redis-py works best with hiredis. Please consider installing
  warnings.warn(msg)


In [4]:
from ray import tune 
model_config = {
            "fcnet_hiddens": [256,256, 256],
            "fcnet_activation": "relu",
            "custom_model" : "fcn",
           "custom_model_config" : {"use_parametric": True,
                                    "env_obs_name": "grid"}
        }
    
    # Configure the environment 

env_config = {
    "env_name": "rte_case14_realistic",
    "keep_observations": ["rho", "gen_p", "load_p","p_or","p_ex","timestep_overflow",  
                                                                      "maintenance", 
                                                                      "topo_vect"],
    #"keep_actions": ["change_bus", "change_line_status"],
    "keep_actions": ["change_bus"],
    "convert_to_tuple": True, # ignored if act_on_singe or medha_actions
    "act_on_single_substation": True, # ignored if medha = True
    "medha_actions": True,
    "rho_threshold": 0,
    "use_parametric": True ,
    "rho_threshold": 0.9
    }

tune_config = {
        "env": "Grid_Gym",
        "env_config": env_config,  # config to pass to env class,
        "model" : model_config,
        "log_level":"WARN",
        "framework": "torch",
        "seed":2137,
        #"lr": tune.grid_search([1e-3, 1e-4]),
        "kl_coeff": 0.2,
        "lambda": 0.94, #tune.quniform(0.94, 0.96, 0.02) ,
        "vf_loss_coeff": 0.95 ,# tune.quniform(0.75,1,0.05),
        "vf_clip_param": 1500,
        "clip_param": 0.25,# tune.quniform(0.1, 0.3, 0.05),
        "rollout_fragment_length": 128, # 16
            "sgd_minibatch_size": 256, # 64
            "train_batch_size": 1024, #2048,
         "ignore_worker_failures": True ,# continue if a worker crashes,
         'num_workers':1
        } 

In [5]:
#grid2op.make(env_config["env_name"])
checkpoint_path = "/Users/blazejmanczak/Desktop/try_this/checkpoint-400"
agent = ppo.PPOTrainer(env=Grid_Gym,
        config = tune_config)
    #      config={
    #     "env_config": env_config,  # config to pass to env class,
    #     #"env_config": {"env_name":"l2rpn\_case14_sandbox"}, 
    #     "model" : model_config,
    #     "log_level":"INFO",
    #     "framework": "torch",
    #     "rollout_fragment_length": 16,
    #         "sgd_minibatch_size": 64,
    #         "train_batch_size": 2048,

    #     "vf_clip_param": 1500

    # })

# agent.restore(checkpoint_path)


(RolloutWorker pid=249) /opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/lightsim2grid/_aux_add_trafo.py:33: UserWarning: There were some Nan in the pp_net.trafo["tap_neutral"], they have been replaced by 0
(RolloutWorker pid=249)   warnings.warn("There were some Nan in the pp_net.trafo[\"tap_neutral\"], they have been replaced by 0")
(RolloutWorker pid=249) /opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/lightsim2grid/_aux_add_trafo.py:41: UserWarning: There were some Nan in the pp_net.trafo["tap_step_percent"], they have been replaced by 0
(RolloutWorker pid=249)   warnings.warn("There were some Nan in the pp_net.trafo[\"tap_step_percent\"], they have been replaced by 0")
(RolloutWorker pid=249) /opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/lightsim2grid/_aux_add_trafo.py:46: UserWarning: There were some Nan in the pp_net.trafo["tap_pos"], they have been replaced by 0
(RolloutWorker pid=249)   warnings.warn("There were some Nan in the pp_net.trafo[\"

(RolloutWorker pid=249) SUBSTATION NUMBER: 0
(RolloutWorker pid=249) Choosing 2 out of 3
(RolloutWorker pid=249) Choosing 3 out of 3
(RolloutWorker pid=249) SUBSTATION NUMBER: 1
(RolloutWorker pid=249) Choosing 3 out of 6
(RolloutWorker pid=249) Choosing 4 out of 6
(RolloutWorker pid=249) Choosing 5 out of 6
(RolloutWorker pid=249) Choosing 6 out of 6
(RolloutWorker pid=249) SUBSTATION NUMBER: 2
(RolloutWorker pid=249) Choosing 2 out of 4
(RolloutWorker pid=249) Choosing 3 out of 4
(RolloutWorker pid=249) Choosing 4 out of 4
(RolloutWorker pid=249) SUBSTATION NUMBER: 3
(RolloutWorker pid=249) Choosing 3 out of 6
(RolloutWorker pid=249) Choosing 4 out of 6
(RolloutWorker pid=249) Choosing 5 out of 6
(RolloutWorker pid=249) Choosing 6 out of 6
(RolloutWorker pid=249) SUBSTATION NUMBER: 4
(RolloutWorker pid=249) Choosing 3 out of 5
(RolloutWorker pid=249) Choosing 4 out of 5
(RolloutWorker pid=249) Choosing 5 out of 5
(RolloutWorker pid=249) SUBSTATION NUMBER: 5
(RolloutWorker pid=249) Ch

In [5]:
agent.restore(checkpoint_path)

AttributeError: Can't get attribute 'KLCoeffMixin' on <module 'ray.rllib.agents.ppo.ppo_torch_policy' from '/opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/ray/rllib/agents/ppo/ppo_torch_policy.py'>

In [6]:
env = Grid_Gym(env_config)

SUBSTATION NUMBER: 0
Choosing 2 out of 3
Choosing 3 out of 3
SUBSTATION NUMBER: 1
Choosing 3 out of 6
Choosing 4 out of 6
Choosing 5 out of 6
Choosing 6 out of 6
SUBSTATION NUMBER: 2
Choosing 2 out of 4
Choosing 3 out of 4
Choosing 4 out of 4
SUBSTATION NUMBER: 3
Choosing 3 out of 6
Choosing 4 out of 6
Choosing 5 out of 6
Choosing 6 out of 6
SUBSTATION NUMBER: 4
Choosing 3 out of 5
Choosing 4 out of 5
Choosing 5 out of 5
SUBSTATION NUMBER: 5
Choosing 3 out of 6
Choosing 4 out of 6
Choosing 5 out of 6
Choosing 6 out of 6
SUBSTATION NUMBER: 6
Choosing 2 out of 3
Choosing 3 out of 3
SUBSTATION NUMBER: 7
Choosing 1 out of 2
Choosing 2 out of 2
SUBSTATION NUMBER: 8
Choosing 3 out of 5
Choosing 4 out of 5
Choosing 5 out of 5
SUBSTATION NUMBER: 9
Choosing 2 out of 3
Choosing 3 out of 3
SUBSTATION NUMBER: 10
Choosing 2 out of 3
Choosing 3 out of 3
SUBSTATION NUMBER: 11
Choosing 2 out of 3
Choosing 3 out of 3
SUBSTATION NUMBER: 12
Choosing 2 out of 4
Choosing 3 out of 4
Choosing 4 out of 4
SUBS

/opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/lightsim2grid/_aux_add_trafo.py:33: UserWarning: There were some Nan in the pp_net.trafo["tap_neutral"], they have been replaced by 0
  warnings.warn("There were some Nan in the pp_net.trafo[\"tap_neutral\"], they have been replaced by 0")
/opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/lightsim2grid/_aux_add_trafo.py:41: UserWarning: There were some Nan in the pp_net.trafo["tap_step_percent"], they have been replaced by 0
  warnings.warn("There were some Nan in the pp_net.trafo[\"tap_step_percent\"], they have been replaced by 0")
/opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/lightsim2grid/_aux_add_trafo.py:46: UserWarning: There were some Nan in the pp_net.trafo["tap_pos"], they have been replaced by 0
  warnings.warn("There were some Nan in the pp_net.trafo[\"tap_pos\"], they have been replaced by 0")


In [16]:
# run until episode ends
from collections import defaultdict

taken_actions = defaultdict(int)

chronics = [0,1,2,3,4]
NB_EPISODES = 10
episode_average_len = []
episode_cum_reward = []

for i in range(NB_EPISODES):
    episode_reward = 0
    episode_len = 0
    done = False
    #env.env_gym.set_id(chronics[i])
    obs = env.reset()

    while not done:
        action = agent.compute_action(obs)
        prev_obs = obs
        #print(action)
        obs, reward, done, info = env.step(action)
        #obs, reward, done, info = env.step()
        episode_reward += reward
        episode_len += 1
        taken_actions[action] += 1

        # if action in do_nothing_actions:
        #     break

    episode_average_len.append(episode_len)
    episode_cum_reward.append(episode_reward)

    print("Epiosde length", episode_len)
    print("Episode reward:", episode_reward)

Epiosde length 810
Episode reward: 13875.832525253296


KeyboardInterrupt: 

In [6]:
# run until episode ends
from collections import defaultdict

taken_actions = defaultdict(int)
NB_EPISODES = 10
episode_average_len = []
episode_cum_reward = []

for i in range(NB_EPISODES):
    episode_reward = 0
    episode_len = 0
    done = False
    obs = env.reset()

    while not done:
        action = agent.compute_action(obs)
        prev_obs = obs
        #print(action)
        obs, reward, done, info = env.step(action)
        #obs, reward, done, info = env.step()
        episode_reward += reward
        episode_len += 1
        taken_actions[action] += 1

        # if action in do_nothing_actions:
        #     break

    episode_average_len.append(episode_len)
    episode_cum_reward.append(episode_reward)

    print("Epiosde length", episode_len)
    print("Episode reward:", episode_reward)

2021-12-03 13:20:11,605	WARNING deprecation.py:39 -- DeprecationWarning: `compute_action` has been deprecated. Use `compute_single_action` instead. This will raise an error in the future!


Epiosde length 5127
Episode reward: 86173.55856609344
Epiosde length 1093
Episode reward: 18410.56779193878
Epiosde length 808
Episode reward: 13815.59400844574
Epiosde length 2823
Episode reward: 47753.05732059479
Epiosde length 6570
Episode reward: 107657.33075332642
Epiosde length 3109
Episode reward: 52618.55894565582
Epiosde length 1095
Episode reward: 18759.457759857178
Epiosde length 523
Episode reward: 9118.27678489685
Epiosde length 4843
Episode reward: 82043.24467372894
Epiosde length 6567
Episode reward: 110163.71011543274


In [13]:
import numpy as np

np.mean(episode_average_len)

/opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3420: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

In [17]:
# run until episode ends
from collections import defaultdict

taken_actions = defaultdict(int)

chronics = [0,1,2,3,4]
NB_EPISODES = 10
episode_average_len = []
episode_cum_reward = []

for i in range(NB_EPISODES):
    episode_reward = 0
    episode_len = 0
    done = False
    #env.env_gym.set_id(chronics[i])
    obs = env.reset()

    while not done:
        action = agent.compute_action(obs)
        prev_obs = obs
        #print(action)
        obs, reward, done, info = env.step(action)
        #obs, reward, done, info = env.step()
        episode_reward += reward
        episode_len += 1
        taken_actions[action] += 1

        # if action in do_nothing_actions:
        #     break

    episode_average_len.append(episode_len)
    episode_cum_reward.append(episode_reward)

    print("Epiosde length", episode_len)
    print("Episode reward:", episode_reward)

defaultdict(int, {0: 4445, 57: 1094})

## Get the mapping between the topo vectors and the do nothing actions


In [15]:
env = Grid_Gym(env_config)

episode_reward = 0
episode_len = 0
done = False
obs = env.reset()
#do_nothing_actions = [0, 25, 28, 54, 65, 90, 91, 92, 103, 104, 105, 106, 110, 111]
topo_to_do_nothing = {}
topo_vects = []
actions_to_take = range(0,106) #[1,2,3,4] #do_nothing_actions #+ [1,2,3,4,5] + [100]
#taken_actions = []


while len(topo_vects) <= 104:
    obs = env.reset()
    # print(obs["grid"])
    # print(taken_actions)
    # if taken_actions==33:
    #     taken_actions += 1
    while not done:
        
        action = actions_to_take[actions_to_take[taken_actions]]
        
        obs, reward, done, info = env.step(action)
        print(obs["grid"]["topo_vect"])
        if done:
            print(info)
        if not done:
            taken_actions += 1
            topo_vects.append(obs["grid"]["topo_vect"])
        

   


/opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/lightsim2grid/_aux_add_trafo.py:33: UserWarning: There were some Nan in the pp_net.trafo["tap_neutral"], they have been replaced by 0
  warnings.warn("There were some Nan in the pp_net.trafo[\"tap_neutral\"], they have been replaced by 0")
/opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/lightsim2grid/_aux_add_trafo.py:41: UserWarning: There were some Nan in the pp_net.trafo["tap_step_percent"], they have been replaced by 0
  warnings.warn("There were some Nan in the pp_net.trafo[\"tap_step_percent\"], they have been replaced by 0")
/opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/lightsim2grid/_aux_add_trafo.py:46: UserWarning: There were some Nan in the pp_net.trafo["tap_pos"], they have been replaced by 0
  warnings.warn("There were some Nan in the pp_net.trafo[\"tap_pos\"], they have been replaced by 0")


SUBSTATION NUMBER: 0
Choosing 2 out of 3
Choosing 3 out of 3
SUBSTATION NUMBER: 1
Choosing 3 out of 6
Choosing 4 out of 6
Choosing 5 out of 6
Choosing 6 out of 6
SUBSTATION NUMBER: 2
Choosing 2 out of 4
Choosing 3 out of 4
Choosing 4 out of 4
SUBSTATION NUMBER: 3
Choosing 3 out of 6
Choosing 4 out of 6
Choosing 5 out of 6
Choosing 6 out of 6
SUBSTATION NUMBER: 4
Choosing 3 out of 5
Choosing 4 out of 5
Choosing 5 out of 5
SUBSTATION NUMBER: 5
Choosing 3 out of 6
Choosing 4 out of 6
Choosing 5 out of 6
Choosing 6 out of 6
SUBSTATION NUMBER: 6
Choosing 2 out of 3
Choosing 3 out of 3
SUBSTATION NUMBER: 7
Choosing 1 out of 2
Choosing 2 out of 2
SUBSTATION NUMBER: 8
Choosing 3 out of 5
Choosing 4 out of 5
Choosing 5 out of 5
SUBSTATION NUMBER: 9
Choosing 2 out of 3
Choosing 3 out of 3
SUBSTATION NUMBER: 10
Choosing 2 out of 3
Choosing 3 out of 3
SUBSTATION NUMBER: 11
Choosing 2 out of 3
Choosing 3 out of 3
SUBSTATION NUMBER: 12
Choosing 2 out of 4
Choosing 3 out of 4
Choosing 4 out of 4
SUBS

KeyboardInterrupt: 

Exception ignored in: <function GymEnv.__del__ at 0x7f8ecd4dcc20>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/grid2op/gym_compat/gymenv.py", line 81, in __del__
    self.close()
  File "/opt/miniconda3/envs/rlib_grid/lib/python3.7/site-packages/grid2op/gym_compat/gymenv.py", line 72, in close
    self.action_space.close()
AttributeError: 'CustomDiscreteActions' object has no attribute 'close'


[array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32),
 array([1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32),
 array([1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32),
 array([1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32),
 array([1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1

In [10]:
import numpy as np
np.unique(np.array(topo_vects), axis = 0).shape, np.array(topo_vects).shape

((32, 56), (34, 56))

array([ 0,  0,  0,  0, -1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0], dtype=int32)

In [54]:
obs

OrderedDict([('gen_p', array([0., 0., 0., 0., 0.], dtype=float32)),
             ('load_p',
              array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)),
             ('p_ex',
              array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                     0., 0., 0.], dtype=float32)),
             ('p_or',
              array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                     0., 0., 0.], dtype=float32)),
             ('rho',
              array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                     0., 0., 0.], dtype=float32)),
             ('timestep_overflow',
              array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    dtype=int32)),
             ('topo_vect',
              array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
                     -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,